<?php
$lang = [
"prod"=>["uz"=>"Tovar" , "ru"=> "товар"],
"cat"=>["uz"=>"Kategoriya" , "ru"=> "категория"],
"sms"=>["uz"=>"Xabarlar" , "ru"=> "сообщение"],
"ordering"=>["uz"=>"Buyurtma qilish" , "ru"=> "заказать"],
"disc"=>["uz"=>"Chegirma" , "ru"=> "скидка"],
"all"=>["uz"=>"Jami" , "ru"=> "итого"],
"block"=>["uz"=>"Blok" , "ru"=> "блок"],
"uzs"=>["uz"=>"So'm" , "ru"=> "сум"],
"photo"=>["uz"=>"Rasmi" , "ru"=> "фото"],
"prod2"=>["uz"=>"Mahsulot" , "ru"=> "товар"],
"amount"=>["uz"=>"Miqdor" , "ru"=> "единица"],
"summa"=>["uz"=>"Summa" , "ru"=> "сумма"],
"min"=>["uz"=>"Minimal" , "ru"=> "минимальный заказ"],
"stock"=>["uz"=>"Mavjud" , "ru"=> "остаток"],
"aksiya"=>["uz"=>"Aksiya" , "ru"=> "акция "],
"action"=>["uz"=>"Amal" , "ru"=> "править"],
"prod_name"=>["uz"=>"Tovar nomi" , "ru"=> "название"],
"cat2"=>["uz"=>"Bo'lim" , "ru"=> "категория"],
"select"=>["uz"=>"Tanlang" , "ru"=> "выбрать"],
"unit"=>["uz"=>"O'lchov birligi" , "ru"=> "единица "],
"ware"=>["uz"=>"Omborda" , "ru"=> "на складе"],
"min2"=>["uz"=>"Minimal buyurtma" , "ru"=> "минимальный заказ"],
""=>["uz"=>"Narxi" , "ru"=> "цена"],
""=>["uz"=>"Tovar rasmi" , "ru"=> "фото"],
""=>["uz"=>"Chegirma" , "ru"=> "скидка"],
""=>["uz"=>"Chegirmasiz" , "ru"=> "без скидки"],
""=>["uz"=>"Shartli" , "ru"=> "условный"],
""=>["uz"=>"Shartsiz" , "ru"=> "без условный"],
""=>["uz"=>"Dan oshsa" , "ru"=> "если превысит"],
""=>["uz"=>"Chegirma miqdori" , "ru"=> "размер скидки"],
""=>["uz"=>"Saqlash" , "ru"=> "сохранить"],
""=>["uz"=>"Mijoz" , "ru"=> "клиент"],
""=>["uz"=>"Sana" , "ru"=> "дата "],
""=>["uz"=>"Holati" , "ru"=> "состояние"],
""=>["uz"=>"Yetgazilgan" , "ru"=> "доставлено"],
""=>["uz"=>"Bekor qilingan" , "ru"=> "отменено"],
""=>["uz"=>"O'zgartirish" , "ru"=> "изменить"],
""=>["uz"=>"Batafsil" , "ru"=> "подробно"],
""=>["uz"=>"Buyurtmani korish" , "ru"=> "открыть заказ"],
""=>["uz"=>"Buyurtma haqida" , "ru"=> "информация заказа"],
""=>["uz"=>"Buyurtma kodi" , "ru"=> "код/номер заказа"],
""=>["uz"=>"Buyurtma holati" , "ru"=> "состояние заказа"],
""=>["uz"=>"Buyurtma sanasi" , "ru"=> "дата заказа"],
""=>["uz"=>"Buyurtmachi" , "ru"=> "заказчик"],
""=>["uz"=>"Etkazib beruvchi" , "ru"=> "доставщик"],
""=>["uz"=>"Telefon raqami" , "ru"=> "номер телефона"],
""=>["uz"=>"Manzil" , "ru"=> "адрес"],
""=>["uz"=>"Buyurtma cheki" , "ru"=> "чек заказа"],
""=>["uz"=>"Barcha maydonlarni to'ldirib qo'shing" , "ru"=> "заполните все поля"],
""=>["uz"=>"O'chirish" , "ru"=> "удалить"],
""=>["uz"=>"Qo'shish" , "ru"=> "добавить"],
""=>["uz"=>"Ma'lumotlar" , "ru"=> "информация "],
""=>["uz"=>"Texnik ishlar" , "ru"=> "технические работы "],
""=>["uz"=>"Kirish" , "ru"=> "вход"]
];
?>